;;; require.el
(require 'evil-init)
(require 'company-init)
(require 'tabnine-init)
(require 'lazy-load)
(require 'rime-init)
(require 'python-init)
(require 'ido-init)
(require 'lsp-init)
(require 'lsp-java-init)
(require 'rust-init)
(require 'ics-init)
(require 'jianwei-init)
(require 'dap-mode-init)
(require 'ui-init)
(require 'go-init)
(require 'eaf-init)
(require 'vue-init)
(require 'web-init)
(require 'org-init)
(require 'telega-init)
(require 'rili-init)
(require 'mu4e-init)
(require 'latex-init)
(require 'php-init)


(provide 'require)
