;;; py-isort-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from py-isort.el

(autoload 'py-isort-region "py-isort" "\
Uses the \"isort\" tool to reformat the current region." t)
(autoload 'py-isort-buffer "py-isort" "\
Uses the \"isort\" tool to reformat the current buffer." t)
(autoload 'py-isort-before-save "py-isort" nil t)
(register-definition-prefixes "py-isort" '("py-isort-"))

;;; End of scraped data

(provide 'py-isort-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; py-isort-autoloads.el ends here
